accounts = {'mypchtryinghard@gmail.com': {'username': 'mypchpwd2', 'password': '12345678', 'usertype': 'patient',
                                          'tpgroup': '1', 'shared_users': '[]', 'url': 'localhost:9107',
                                          'fake_response': 'You shall have access to watermarked data from ...',
                                          'fake_post': 'You are a RW user shall be able to upload valid data ...'},
            'mypchpwd1@gmail.com':      {'username': 'mypchpwd1', 'password': '12345678', 'usertype': 'patient',
                                          'clinic': '1', 'shared_users': '[mypchpwd2@gmail.com]', 'url': 'localhost:9107',
                                          'fake_response': 'You have full access to watermarked data from own account. You shall also have access to watermarked data from mypchpwd2@gmail.com',
                                          'fake_post': 'You are a RW user and is allowed to send POST requests ...'},
            'mypchpwd2@gmail.com':      {'username': 'mypchpwd2', 'password': '12345678', 'usertype': 'patient',
                                          'clinic': '1', 'shared_users': '[mypchpwd3@gmail.com]', 'url': 'localhost:9107',
                                          'fake_response': 'You have full access to data from own account. You shall also have access to watermarked data from mypchpwd3@gmail.com',
                                          'fake_post': 'You are a RW user and is allowed to send POST requests ...'},
            'mypchpwd3@gmail.com':      {'username': 'mypchpwd3', 'password': '12345678', 'usertype': 'patient',
                                          'clinic': '2', 'shared_users': '[]', 'url': 'localhost:9107',
                                          'fake_response': 'You have full access to data from own account. You shall not be able to access data from others',
                                          'fake_post': 'You are a RW user and is allowed to send POST requests ...'},
            'mypchc1d1@gmail.com':      {'username': 'mypchc1d1', 'password': '12345678', 'usertype': 'advisor',
                                          'clinic': '1', 'shared_users': '[]', 'url': 'localhost:9107',
                                          'fake_response': 'You have full access to watermarked data from all patients in the specific clinic',
                                          'fake_post': 'You are a RO user and is NOT allowed to send POST requests ...'},
            'mypchc1d2@gmail.com':      {'username': 'mypchc1d2', 'password': '12345678', 'usertype': 'advisor',
                                          'clinic': '1', 'shared_users': '[]', 'url': 'localhost:9107',
                                          'fake_response': 'You have full access to watermarked data from all patients in the specific clinic. You also have access to aggregated data from a patient in another clinic',
                                          'fake_post': 'You are a RO user and is NOT allowed to send POST requests ...'},
            'mypchr1u1@gmail.com':      {'username': 'mypchr1u1', 'password': '12345678', 'usertype': 'research',
                                          'clinic': '', 'shared_users': '[]', 'url': 'localhost:9107',
                                          'fake_response': 'You have annonymouns and partial access to data from some patients',
                                          'fake_post': 'You are a RO user and is NOT allowed to send POST requests ...'},
            'mypchi1u1@gmail.com':      {'username': 'mypchi1u1', 'password': '12345678', 'usertype': '3party',
                                          'clinic': '', 'shared_users': '[]', 'url': 'localhost:9107',
                                          'fake_response': 'You have partial (time and data types) access to watermarked data from some patients',
                                          'fake_post': 'You are a RO user and is NOT allowed to send POST requests ...'},
            'mypchi1u2@gmail.com':      {'username': 'mypchi1u2', 'password': '12345678', 'usertype': '3party',
                                          'clinic': '', 'shared_users': '[]', 'url': 'localhost:9107',
                                          'fake_response': 'You have partial (time and data types) access to watermarked data from some patients',
                                          'fake_post': 'You are a RO user and is NOT allowed to send POST requests ...'},
            'mypchi2u1@gmail.com':      {'username': 'mypchi2u1', 'password': '12345678', 'usertype': '3party',
                                          'clinic': '', 'shared_users': '[]', 'url': 'localhost:9107',
                                          'fake_response': 'You have partial (time and data types) access to watermarked data from some patients',
                                          'fake_post': 'You are a RO user and is NOT allowed to send POST requests ...'}}
